### ISSUE TITLE
I got an error

### ISSUE THREAD

**Issue by haoxl3** [Pixilib/Dat_Scan_Viewer#3]
I dragged and dropped a DICom file, error reported
<img width="681" alt="image" src="https://user-images.githubusercontent.com/15046133/179746753-bb4da95c-f3ac-49a0-8935-0aa086779da2.png">
What type of image should I drag and drop? Could you please provide me with a working example image. my email is  1098262516@qq.com 
thank you

**Comment by salimkanoun** [comment]
Sorry we can't, we are at an exploration stage, there is nothing functional help, we plan to make Cornerstone/OHIF developpement later this year but we have nothing for now
